// 국가 목록 (주요 국가들)
const countries = [
    { code: 'KR', name: 'South Korea', nameKo: '대한민국', flag: '🇰🇷' },
    { code: 'US', name: 'United States', nameKo: '미국', flag: '🇺🇸' },
    { code: 'JP', name: 'Japan', nameKo: '일본', flag: '🇯🇵' },
    { code: 'CN', name: 'China', nameKo: '중국', flag: '🇨🇳' },
    { code: 'GB', name: 'United Kingdom', nameKo: '영국', flag: '🇬🇧' },
    { code: 'DE', name: 'Germany', nameKo: '독일', flag: '🇩🇪' },
    { code: 'FR', name: 'France', nameKo: '프랑스', flag: '🇫🇷' },
    { code: 'CA', name: 'Canada', nameKo: '캐나다', flag: '🇨🇦' },
    { code: 'AU', name: 'Australia', nameKo: '호주', flag: '🇦🇺' },
    { code: 'BR', name: 'Brazil', nameKo: '브라질', flag: '🇧🇷' },
    { code: 'IN', name: 'India', nameKo: '인도', flag: '🇮🇳' },
    { code: 'RU', name: 'Russia', nameKo: '러시아', flag: '🇷🇺' },
    { code: 'IT', name: 'Italy', nameKo: '이탈리아', flag: '🇮🇹' },
    { code: 'ES', name: 'Spain', nameKo: '스페인', flag: '🇪🇸' },
    { code: 'MX', name: 'Mexico', nameKo: '멕시코', flag: '🇲🇽' },
    { code: 'NL', name: 'Netherlands', nameKo: '네덜란드', flag: '🇳🇱' },
    { code: 'SE', name: 'Sweden', nameKo: '스웨덴', flag: '🇸🇪' },
    { code: 'NO', name: 'Norway', nameKo: '노르웨이', flag: '🇳🇴' },
    { code: 'DK', name: 'Denmark', nameKo: '덴마크', flag: '🇩🇰' },
    { code: 'FI', name: 'Finland', nameKo: '핀란드', flag: '🇫🇮' },
    { code: 'CH', name: 'Switzerland', nameKo: '스위스', flag: '🇨🇭' },
    { code: 'AT', name: 'Austria', nameKo: '오스트리아', flag: '🇦🇹' },
    { code: 'BE', name: 'Belgium', nameKo: '벨기에', flag: '🇧🇪' },
    { code: 'PL', name: 'Poland', nameKo: '폴란드', flag: '🇵🇱' },
    { code: 'CZ', name: 'Czech Republic', nameKo: '체코', flag: '🇨🇿' },
    { code: 'HU', name: 'Hungary', nameKo: '헝가리', flag: '🇭🇺' },
    { code: 'RO', name: 'Romania', nameKo: '루마니아', flag: '🇷🇴' },
    { code: 'BG', name: 'Bulgaria', nameKo: '불가리아', flag: '🇧🇬' },
    { code: 'HR', name: 'Croatia', nameKo: '크로아티아', flag: '🇭🇷' },
    { code: 'SI', name: 'Slovenia', nameKo: '슬로베니아', flag: '🇸🇮' },
    { code: 'SK', name: 'Slovakia', nameKo: '슬로바키아', flag: '🇸🇰' },
    { code: 'LT', name: 'Lithuania', nameKo: '리투아니아', flag: '🇱🇹' },
    { code: 'LV', name: 'Latvia', nameKo: '라트비아', flag: '🇱🇻' },
    { code: 'EE', name: 'Estonia', nameKo: '에스토니아', flag: '🇪🇪' },
    { code: 'IE', name: 'Ireland', nameKo: '아일랜드', flag: '🇮🇪' },
    { code: 'PT', name: 'Portugal', nameKo: '포르투갈', flag: '🇵🇹' },
    { code: 'GR', name: 'Greece', nameKo: '그리스', flag: '🇬🇷' },
    { code: 'TR', name: 'Turkey', nameKo: '터키', flag: '🇹🇷' },
    { code: 'UA', name: 'Ukraine', nameKo: '우크라이나', flag: '🇺🇦' },
    { code: 'BY', name: 'Belarus', nameKo: '벨라루스', flag: '🇧🇾' },
    { code: 'MD', name: 'Moldova', nameKo: '몰도바', flag: '🇲🇩' },
    { code: 'GE', name: 'Georgia', nameKo: '조지아', flag: '🇬🇪' },
    { code: 'AM', name: 'Armenia', nameKo: '아르메니아', flag: '🇦🇲' },
    { code: 'AZ', name: 'Azerbaijan', nameKo: '아제르바이잔', flag: '🇦🇿' },
    { code: 'KZ', name: 'Kazakhstan', nameKo: '카자흐스탄', flag: '🇰🇿' },
    { code: 'UZ', name: 'Uzbekistan', nameKo: '우즈베키스탄', flag: '🇺🇿' },
    { code: 'KG', name: 'Kyrgyzstan', nameKo: '키르기스스탄', flag: '🇰🇬' },
    { code: 'TJ', name: 'Tajikistan', nameKo: '타지키스탄', flag: '🇹🇯' },
    { code: 'TM', name: 'Turkmenistan', nameKo: '투르크메니스탄', flag: '🇹🇲' },
    { code: 'AF', name: 'Afghanistan', nameKo: '아프가니스탄', flag: '🇦🇫' },
    { code: 'PK', name: 'Pakistan', nameKo: '파키스탄', flag: '🇵🇰' },
    { code: 'BD', name: 'Bangladesh', nameKo: '방글라데시', flag: '🇧🇩' },
    { code: 'LK', name: 'Sri Lanka', nameKo: '스리랑카', flag: '🇱🇰' },
    { code: 'NP', name: 'Nepal', nameKo: '네팔', flag: '🇳🇵' },
    { code: 'BT', name: 'Bhutan', nameKo: '부탄', flag: '🇧🇹' },
    { code: 'MV', name: 'Maldives', nameKo: '몰디브', flag: '🇲🇻' },
    { code: 'TH', name: 'Thailand', nameKo: '태국', flag: '🇹🇭' },
    { code: 'VN', name: 'Vietnam', nameKo: '베트남', flag: '🇻🇳' },
    { code: 'LA', name: 'Laos', nameKo: '라오스', flag: '🇱🇦' },
    { code: 'KH', name: 'Cambodia', nameKo: '캄보디아', flag: '🇰🇭' },
    { code: 'MM', name: 'Myanmar', nameKo: '미얀마', flag: '🇲🇲' },
    { code: 'MY', name: 'Malaysia', nameKo: '말레이시아', flag: '🇲🇾' },
    { code: 'SG', name: 'Singapore', nameKo: '싱가포르', flag: '🇸🇬' },
    { code: 'ID', name: 'Indonesia', nameKo: '인도네시아', flag: '🇮🇩' },
    { code: 'PH', name: 'Philippines', nameKo: '필리핀', flag: '🇵🇭' },
    { code: 'TW', name: 'Taiwan', nameKo: '대만', flag: '🇹🇼' },
    { code: 'HK', name: 'Hong Kong', nameKo: '홍콩', flag: '🇭🇰' },
    { code: 'MO', name: 'Macau', nameKo: '마카오', flag: '🇲🇴' },
    { code: 'MN', name: 'Mongolia', nameKo: '몽골', flag: '🇲🇳' },
    { code: 'NZ', name: 'New Zealand', nameKo: '뉴질랜드', flag: '🇳🇿' },
    { code: 'FJ', name: 'Fiji', nameKo: '피지', flag: '🇫🇯' },
    { code: 'PG', name: 'Papua New Guinea', nameKo: '파푸아뉴기니', flag: '🇵🇬' },
    { code: 'SB', name: 'Solomon Islands', nameKo: '솔로몬 제도', flag: '🇸🇧' },
    { code: 'VU', name: 'Vanuatu', nameKo: '바누아투', flag: '🇻🇺' },
    { code: 'NC', name: 'New Caledonia', nameKo: '뉴칼레도니아', flag: '🇳🇨' },
    { code: 'PF', name: 'French Polynesia', nameKo: '프랑스령 폴리네시아', flag: '🇵🇫' },
    { code: 'TO', name: 'Tonga', nameKo: '통가', flag: '🇹🇴' },
    { code: 'WS', name: 'Samoa', nameKo: '사모아', flag: '🇼🇸' },
    { code: 'KI', name: 'Kiribati', nameKo: '키리바시', flag: '🇰🇮' },
    { code: 'TV', name: 'Tuvalu', nameKo: '투발루', flag: '🇹🇻' },
    { code: 'NR', name: 'Nauru', nameKo: '나우루', flag: '🇳🇷' },
    { code: 'PW', name: 'Palau', nameKo: '팔라우', flag: '🇵🇼' },
    { code: 'MH', name: 'Marshall Islands', nameKo: '마셜 제도', flag: '🇲🇭' },
    { code: 'FM', name: 'Micronesia', nameKo: '미크로네시아', flag: '🇫🇲' },
    { code: 'GU', name: 'Guam', nameKo: '괌', flag: '🇬🇺' },
    { code: 'MP', name: 'Northern Mariana Islands', nameKo: '북마리아나 제도', flag: '🇲🇵' },
    { code: 'AS', name: 'American Samoa', nameKo: '미국령 사모아', flag: '🇦🇸' },
    { code: 'CK', name: 'Cook Islands', nameKo: '쿡 제도', flag: '🇨🇰' },
    { code: 'NU', name: 'Niue', nameKo: '니우에', flag: '🇳🇺' },
    { code: 'TK', name: 'Tokelau', nameKo: '토켈라우', flag: '🇹🇰' },
    { code: 'WF', name: 'Wallis and Futuna', nameKo: '왈리스 푸투나', flag: '🇼🇫' },
    { code: 'PN', name: 'Pitcairn Islands', nameKo: '핏케언 제도', flag: '🇵🇳' },
    { code: 'AQ', name: 'Antarctica', nameKo: '남극', flag: '🇦🇶' },
    { code: 'BV', name: 'Bouvet Island', nameKo: '부베 섬', flag: '🇧🇻' },
    { code: 'TF', name: 'French Southern Territories', nameKo: '프랑스령 남부 지역', flag: '🇹🇫' },
    { code: 'HM', name: 'Heard and McDonald Islands', nameKo: '허드 맥도널드 제도', flag: '🇭🇲' },
    { code: 'GS', name: 'South Georgia and South Sandwich Islands', nameKo: '사우스조지아 사우스샌드위치 제도', flag: '🇬🇸' },
    { code: 'IO', name: 'British Indian Ocean Territory', nameKo: '영국령 인도양 지역', flag: '🇮🇴' },
    { code: 'FK', name: 'Falkland Islands', nameKo: '포클랜드 제도', flag: '🇫🇰' },
    { code: 'GI', name: 'Gibraltar', nameKo: '지브롤터', flag: '🇬🇮' },
    { code: 'AD', name: 'Andorra', nameKo: '안도라', flag: '🇦🇩' },
    { code: 'LI', name: 'Liechtenstein', nameKo: '리히텐슈타인', flag: '🇱🇮' },
    { code: 'MC', name: 'Monaco', nameKo: '모나코', flag: '🇲🇨' },
    { code: 'SM', name: 'San Marino', nameKo: '산마리노', flag: '🇸🇲' },
    { code: 'VA', name: 'Vatican City', nameKo: '바티칸', flag: '🇻🇦' },
    { code: 'MT', name: 'Malta', nameKo: '몰타', flag: '🇲🇹' },
    { code: 'CY', name: 'Cyprus', nameKo: '키프로스', flag: '🇨🇾' },
    { code: 'IS', name: 'Iceland', nameKo: '아이슬란드', flag: '🇮🇸' },
    { code: 'LU', name: 'Luxembourg', nameKo: '룩셈부르크', flag: '🇱🇺' },
    { code: 'AL', name: 'Albania', nameKo: '알바니아', flag: '🇦🇱' },
    { code: 'MK', name: 'North Macedonia', nameKo: '북마케도니아', flag: '🇲🇰' },
    { code: 'ME', name: 'Montenegro', nameKo: '몬테네그로', flag: '🇲🇪' },
    { code: 'BA', name: 'Bosnia and Herzegovina', nameKo: '보스니아 헤르체고비나', flag: '🇧🇦' },
    { code: 'RS', name: 'Serbia', nameKo: '세르비아', flag: '🇷🇸' },
    { code: 'XK', name: 'Kosovo', nameKo: '코소보', flag: '🇽🇰' },
    { code: 'IL', name: 'Israel', nameKo: '이스라엘', flag: '🇮🇱' },
    { code: 'PS', name: 'Palestine', nameKo: '팔레스타인', flag: '🇵🇸' },
    { code: 'JO', name: 'Jordan', nameKo: '요르단', flag: '🇯🇴' },
    { code: 'LB', name: 'Lebanon', nameKo: '레바논', flag: '🇱🇧' },
    { code: 'SY', name: 'Syria', nameKo: '시리아', flag: '🇸🇾' },
    { code: 'IQ', name: 'Iraq', nameKo: '이라크', flag: '🇮🇶' },
    { code: 'KW', name: 'Kuwait', nameKo: '쿠웨이트', flag: '🇰🇼' },
    { code: 'SA', name: 'Saudi Arabia', nameKo: '사우디아라비아', flag: '🇸🇦' },
    { code: 'AE', name: 'United Arab Emirates', nameKo: '아랍에미리트', flag: '🇦🇪' },
    { code: 'QA', name: 'Qatar', nameKo: '카타르', flag: '🇶🇦' },
    { code: 'BH', name: 'Bahrain', nameKo: '바레인', flag: '🇧🇭' },
    { code: 'OM', name: 'Oman', nameKo: '오만', flag: '🇴🇲' },
    { code: 'YE', name: 'Yemen', nameKo: '예멘', flag: '🇾🇪' },
    { code: 'EG', name: 'Egypt', nameKo: '이집트', flag: '🇪🇬' },
    { code: 'SD', name: 'Sudan', nameKo: '수단', flag: '🇸🇩' },
    { code: 'SS', name: 'South Sudan', nameKo: '남수단', flag: '🇸🇸' },
    { code: 'LY', name: 'Libya', nameKo: '리비아', flag: '🇱🇾' },
    { code: 'TN', name: 'Tunisia', nameKo: '튀니지', flag: '🇹🇳' },
    { code: 'DZ', name: 'Algeria', nameKo: '알제리', flag: '🇩🇿' },
    { code: 'MA', name: 'Morocco', nameKo: '모로코', flag: '🇲🇦' },
    { code: 'EH', name: 'Western Sahara', nameKo: '서사하라', flag: '🇪🇭' },
    { code: 'MR', name: 'Mauritania', nameKo: '모리타니', flag: '🇲🇷' },
    { code: 'ML', name: 'Mali', nameKo: '말리', flag: '🇲🇱' },
    { code: 'BF', name: 'Burkina Faso', nameKo: '부르키나파소', flag: '🇧🇫' },
    { code: 'NE', name: 'Niger', nameKo: '니제르', flag: '🇳🇪' },
    { code: 'TD', name: 'Chad', nameKo: '차드', flag: '🇹🇩' },
    { code: 'NG', name: 'Nigeria', nameKo: '나이지리아', flag: '🇳🇬' },
    { code: 'CM', name: 'Cameroon', nameKo: '카메룬', flag: '🇨🇲' },
    { code: 'GQ', name: 'Equatorial Guinea', nameKo: '적도기니', flag: '🇬🇶' },
    { code: 'GA', name: 'Gabon', nameKo: '가봉', flag: '🇬🇦' },
    { code: 'CG', name: 'Republic of the Congo', nameKo: '콩고 공화국', flag: '🇨🇬' },
    { code: 'CD', name: 'Democratic Republic of the Congo', nameKo: '콩고 민주공화국', flag: '🇨🇩' },
    { code: 'CF', name: 'Central African Republic', nameKo: '중앙아프리카공화국', flag: '🇨🇫' },
    { code: 'ST', name: 'São Tomé and Príncipe', nameKo: '상투메 프린시페', flag: '🇸🇹' },
    { code: 'GW', name: 'Guinea-Bissau', nameKo: '기니비사우', flag: '🇬🇼' },
    { code: 'GN', name: 'Guinea', nameKo: '기니', flag: '🇬🇳' },
    { code: 'SL', name: 'Sierra Leone', nameKo: '시에라리온', flag: '🇸🇱' },
    { code: 'LR', name: 'Liberia', nameKo: '라이베리아', flag: '🇱🇷' },
    { code: 'CI', name: 'Ivory Coast', nameKo: '코트디부아르', flag: '🇨🇮' },
    { code: 'GH', name: 'Ghana', nameKo: '가나', flag: '🇬🇭' },
    { code: 'TG', name: 'Togo', nameKo: '토고', flag: '🇹🇬' },
    { code: 'BJ', name: 'Benin', nameKo: '베냉', flag: '🇧🇯' },
    { code: 'SN', name: 'Senegal', nameKo: '세네갈', flag: '🇸🇳' },
    { code: 'GM', name: 'Gambia', nameKo: '감비아', flag: '🇬🇲' },
    { code: 'CV', name: 'Cape Verde', nameKo: '카보베르데', flag: '🇨🇻' },
    { code: 'MZ', name: 'Mozambique', nameKo: '모잠비크', flag: '🇲🇿' },
    { code: 'ZW', name: 'Zimbabwe', nameKo: '짐바브웨', flag: '🇿🇼' },
    { code: 'BW', name: 'Botswana', nameKo: '보츠와나', flag: '🇧🇼' },
    { code: 'NA', name: 'Namibia', nameKo: '나미비아', flag: '🇳🇦' },
    { code: 'ZA', name: 'South Africa', nameKo: '남아프리카공화국', flag: '🇿🇦' },
    { code: 'LS', name: 'Lesotho', nameKo: '레소토', flag: '🇱🇸' },
    { code: 'SZ', name: 'Eswatini', nameKo: '에스와티니', flag: '🇸🇿' },
    { code: 'MG', name: 'Madagascar', nameKo: '마다가스카르', flag: '🇲🇬' },
    { code: 'MU', name: 'Mauritius', nameKo: '모리셔스', flag: '🇲🇺' },
    { code: 'SC', name: 'Seychelles', nameKo: '세이셸', flag: '🇸🇨' },
    { code: 'KM', name: 'Comoros', nameKo: '코모로', flag: '🇰🇲' },
    { code: 'DJ', name: 'Djibouti', nameKo: '지부티', flag: '🇩🇯' },
    { code: 'SO', name: 'Somalia', nameKo: '소말리아', flag: '🇸🇴' },
    { code: 'ET', name: 'Ethiopia', nameKo: '에티오피아', flag: '🇪🇹' },
    { code: 'ER', name: 'Eritrea', nameKo: '에리트레아', flag: '🇪🇷' },
    { code: 'KE', name: 'Kenya', nameKo: '케냐', flag: '🇰🇪' },
    { code: 'TZ', name: 'Tanzania', nameKo: '탄자니아', flag: '🇹🇿' },
    { code: 'UG', name: 'Uganda', nameKo: '우간다', flag: '🇺🇬' },
    { code: 'RW', name: 'Rwanda', nameKo: '르완다', flag: '🇷🇼' },
    { code: 'BI', name: 'Burundi', nameKo: '부룬디', flag: '🇧🇮' },
    { code: 'MW', name: 'Malawi', nameKo: '말라위', flag: '🇲🇼' },
    { code: 'ZM', name: 'Zambia', nameKo: '잠비아', flag: '🇿🇲' },
    { code: 'AO', name: 'Angola', nameKo: '앙골라', flag: '🇦🇴' }
];

// 국가 코드로 국가 정보 찾기
function findCountryByCode(code) {
    return countries.find(country => country.code === code);
}

// 국가명으로 국가 정보 찾기
function findCountryByName(name) {
    return countries.find(country => 
        country.name.toLowerCase() === name.toLowerCase() || 
        country.nameKo === name
    );
}

// 언어에 따른 국가명 반환
function getCountryName(country, language = 'en') {
    if (language === 'ko') {
        return country.nameKo;
    }
    return country.name;
}

// 국가 목록을 언어별로 정렬하여 반환
function getSortedCountries(language = 'en') {
    return countries.sort((a, b) => {
        const nameA = getCountryName(a, language);
        const nameB = getCountryName(b, language);
        return nameA.localeCompare(nameB);
    });
}